#spring.application.name=shop-pos-system
#
#
#
#server.port=${PORT:5000}
#server.address=0.0.0.0
#
#spring.jpa.hibernate.ddl-auto=update
#spring.datasource.url=jdbc:mysql://${MYSQLHOST:localhost}:${MYSQLPORT:3306}/${MYSQLDATABASE:shop_pos}
#spring.datasource.username=${MYSQLUSER:root}
#spring.datasource.password=${MYSQLPASSWORD:@.ADgjm96801}
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect



spring.application.name=shop-pos-system

# Server Configuration
server.port=${PORT:5000}
server.address=0.0.0.0

# Database Configuration (Public URL ??????? ????)
# internal address (mysql.railway.internal) ?? ???? public proxy ??????? ????
spring.datasource.url=jdbc:mysql://shuttle.proxy.rlwy.net:23161/railway
spring.datasource.username=root
spring.datasource.password=OvDVJeJtQDRSXKzhZZIhggoyQApxiSzc
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate Properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true